modLoader = "javafml"
loaderVersion = "[${forge_version},)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "examplemod"
version = "${0.0.1}"
displayName = "Create: Creatingness"
authors = "Curly Fries"
description = '''
A Create Mod addon that adds.
'''
logoFile = "icon.png"

[[dependencies.examplemod]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.examplemod]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.examplemod]]
modId="create"
mandatory=true
versionRange="${create_version}"
ordering="NONE"
side="BOTH"
